version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: "mysql_container"
    ports:
      - "9090:3306"
    volumes:
      - ./app/mysql/conf.d:/etc/mysql/conf.d
      - ./app/mysql/data:/var/lib/mysql
    env_file: .env
    environment:
      TZ: Asia/Seoul
    restart: always

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server_container
    ports:
      - "8000:8000"
    env_file: .env
    command: uvicorn app.app:app --host 127.0.0.1 --port 8000 --reload
    restart: always